# basic yaml file with configuration that rarely changes

debug: False
wandb: 
    log: True
    project: 'MICCAI2023-extension'
fs: 
    repo_root: '../../'
    root: '../../../../../'
data: 
    brain: 
        data_path: 'data/conp-dataset/projects/calgary-campinas/CC359/Reconstructed/'
    heart:
        acdc:
            data_path: 'data/nnUNet_preprocessed/Task500_ACDC/'
        mnm:
            data_path: 'data/nnUNet_preprocessed/Task679_MNM/'
            selection: 'all_cases'
unet:
    weight_dir: '../../pre-trained/trained_UNets/'
    log_dir: '../../pre-trained/trainer_logs/'
    brain: 
        pre: 'calgary_unet'
        n_chans_in: 1
        n_filters_init: 8
        n_chans_out: 1
        training: 
            train_site: 6
            augment: True
            validation: True
            batch_size: 32
            num_batches_per_epoch: 250
            epochs: 250
            patience: 4
            lr: 0.001
    heart: 
        pre: 'acdc_unet'
        n_chans_in: 1
        n_filters_init: 8
        n_chans_out: 4
        training: 
            augment: True
            validation: True
            batch_size: 32
            num_batches_per_epoch: 250
            num_val_batches_per_epoch: 50
            epochs: 250
            patience: 4
            lr: 0.001