


brain:
  unet:
    train:
      volume_wise: True
      batch_size: 1
      collate: volume
    val:
      volume_wise: True
      batch_size: 1
      collate: volume
    test:
      volume_wise: True
      batch_size: 1
      collate: volume
  image:
    train:
      volume_wise: False
      batch_size: 32
      collate: default
    val:
      volume_wise: True
      batch_size: 1
      collate: volume
    test:
      volume_wise: True
      batch_size: 1
      collate: volume
  pixel:
    train:
      volume_wise: False
      batch_size: 32
      collate: default
    val:
      volume_wise: False
      batch_size: 32
      collate: default
    test:
      volume_wise: False
      batch_size: 32
      collate: default

heart:
  volume_wise: False
  batch_size: 1
  collate: default