
# Hyperparams
model: 'ResDAE'
name: 'None'
identity_swivels: None
arch:
  depth: 20
trainer:
  batch_size: 32
  # augment: False
  difference: True
  reconstruction: True
  loss: huber
  target: output
  lr: 1e-4
  patience: 8
  n_epochs: 250
  num_batches_per_epoch: 250
  num_val_batches_per_epoch: 50
  disabled_ids: None
  
# outputs
plot_dir: ../experiments/unet/calgary/logs/