
# Hyperparams
model: 'ResMAE'
name: 'None'
identity_swivels: None
training: 'mae'
arch:
  depth: 20
  p: 0.6
  mask: 'per_channel'
trainer:
  batch_size: 32
  difference: true
  reconstruction: true
  loss: huber
  target: output
  lr: 1e-4
  patience: 8
  n_epochs: 250
  num_batches_per_epoch: 250
  num_val_batches_per_epoch: 50
  include_orig_data: false
  disabled_ids: None

# weights
weight_dir: '../../pre-trained-tmp/trained_AEs/'
log_dir: '../../pre-trained-tmp/trainer_logs/'

# outputs
plot_dir: ../experiments/unet/calgary/logs/